default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root_dev
  password: 1234
  socket: /tmp/mysql.sock # for mac
  #socket: /var/run/mysqld/mysqld.sock # for ubuntu

development:
  <<: *default
<<<<<<< HEAD
  database: rubysauce_development
=======
  database: rubysauce_dev
>>>>>>> 0c54a32d5707e0c5d4f84eac65e4db15e65acbb6


test:
  <<: *default
  database: rubysauce_test

production:
  <<: *default
  database: rubysauce_cms
